### ISSUE TITLE
Write Info page

### ISSUE THREAD

**Issue by rich-pixley** [rnkn/fountain-mode#106]
The image looks cool.  But I can’t, from buffer mode info alone, figure out the basic paradigms, usage, or how to get from one to another. This makes fountain-mode a toy for me. Wish I knew how to do what it looks like someone is doing in the picture. That would make it a superior grade professional tool.

**Comment by rnkn** [comment]
I'm slowly working on an Info manual. Obviously it's not a high priority for me because I know how it all works already (and I'm the only maintainer).

The core idea of the Fountain syntax is just to write what looks like a screenplay and it will be parsed as a screenplay. There are some syntactic bells & whistles, but mostly if you just write how a screenplay looks you can't go wrong. All the syntax info is at https://fountain.io but I do plan to include this in an Info manual too, eventually.

As far as other functions, like navigation, structure editing, exporting, etc., you should be able to get a pretty good idea what's what from the Fountain menu (which I've tried to make mimic the Org Mode menu).

Lemme know if there's anything specific you're trying to do and can't figure it out.

**Comment by rnkn** [comment]
Something that would help me out is if you feel something is confusing, add a page to the wiki with a note about it. I plan to use the wiki as the basis for the Texinfo file.

**Comment by rnkn** [comment]
For anyone stumbling across this issue, basically I have no desire to write documentation. Emacs is a self-documenting editor, so it's not difficult to find documentation on all the commands with `C-h f`, or `C-h m` for an overview of everything.

It would be nice to have a Texinfo manual, so if anyone wants to add documentation, please add pages to the wiki. At some point I'll then clean this up, make sure it's accurate, and convert to Texinfo.

**Comment by kohled** [comment]
I can try to help with this as I have substantial experience with fountain and screenwriting but very limited experience with emacs and fountain-mode (and github for that matter.) Might be a useful perspective. Taking note of my questions and learning process as I incorporate fountain-mode into my professional workflow.

To ensure I understand correctly, whatever I write up, I just add a new page to the wiki and publish it?

**Comment by rnkn** [comment]
@kohled sure, that would be cool :)

The wiki approach is gonna be too difficult because I've since tested converting markdown -> texinfo and it's awful. Instead I've done a bit of preliminary on an [Org Mode](https://orgmode.org) file which I've just pushed to master: https://github.com/rnkn/fountain-mode/blob/master/docs/fountain-mode.org

The thing I'd most appreciate is the "Script Elements" section, which should just be how to write a script in the Fountain syntax. (I'll add all the stuff specific to Fountain Mode, but feel free to add anything really.)

The best way to edit this is in Emacs. Org Mode is part of Emacs. It is hideously complex but you can ignore 99% of it. Fork this repository and clone it to your computer, then edit the `docs/fountain-mode.org` file. To see your progress, you'll need to customize the option `org-export-backends` and check Texinfo. Then you can export with to Info with `C-c C-e i i`. This won't automatically be included in the Info path, so to see it, `C-u C-h i fountain-mode.info RET`.

I've added ignore paths to .gitignore so you won't accidentally commit the output files yet.

Then push back to Github and open a pull request. Let me know if you run into anything confusing.

How's that sound?

**Comment by kohled** [comment]
Sounds perfect.

Thanks for detailing the steps. Sage wisdom to ignore 99% of org-mode. Bit of a mind-blowing program. Perhaps one day.

I've got fountain-mode.org loaded and `org-export-backends` customized. Appreciate the foresight to beginner-proof the doc through .gitignore.

Will focus on the "Script Elements" section per guidance. Few ideas came up like a brief answer to-- "Why Fountain?" My intention is to provide raw material for you to shape as you see fit.

Unrelated sidenote: granular customization of syntax highlighting is a super nice touch.

More anon. And on and on.

**Comment by rnkn** [comment]
A "Why Fountain?" part sounds great. Add whatever you like. I'm disadvantaged in that I'm so familiar with the software that it's harder for me to know what is obvious and what isn't to everyone else.

**Comment by kohled** [comment]
I relate to the disadvantage of familiarity. Happens with every screenplay I write or anything else I go deeply into. From what modest amount of code I can read, you've gone *deep*.

Drafting some ideas to send over to you. Need to read other Texinfo manuals to get a general sense of style. Might be a bit before I open a pull request but sooner rather than later.

**Comment by rnkn** [comment]
While not complete, the info page is now no longer missing any nodes, and is available online and via Emacs Info documentation browser.

https://www.fountain-mode.org
