### ISSUE TITLE
Setting Action Alignment / Customizing Export Alignment

### ISSUE THREAD

**Issue by LittleHouse75** [rnkn/fountain-mode#27]
Hello!  Your Fountain mode is incredibly awesome... It may just actually pull me away from fountain with Sublime Text.  Two quick questions.  First, can the alignment of action elements be set?  I see options for other elements (character, dialogue, etc.), but not action.  I use Fountain for playwriting, which usually has wide dialogue and narrow narration (basically the opposite of screenwriting).  Also, can I hack the alignment for PDF/HTML export for the same reasons?  Thanks much!

**Comment by rnkn** [comment]
Thanks, glad it's getting some use. I've never written a stage play so I had to look up the formatting. Is this an accurate representation? http://ptfaculty.gordonstate.edu/lking/CPF_play_formatting2.pdf

Currently no, the action elements can't be aligned within Emacs. I never actually made action an element *per se* rather everything that's not any other element is counted as action. That said, I'll make sure to fix this come version 2.0.

Exporting is another story since it's just CSS. Customize the value of `fountain-export-style-template`:
~~~css
p.action {
    margin-left: 2.5in;    /* this line added */
    white-space: pre-wrap;
    orphans: ${action-orphans};
    widows: ${action-widows};
}
~~~

I'm currently rewriting a lot of the internals, so please let me know if there are any other compatibility issues with playwriting.

**Comment by LittleHouse75** [comment]
Thanks for the quick reply!  I'll look forward to 2.0, but I'll go with
your suggestion of editing the CSS export style and make good use of the
Fountain mode as is.

With regard to playwriting format, I've never found a "standard".  Every
screenwriting app seems to provide slightly different stageplay templates,
though they are all similar to the link you've provided.  I'm personally
enamored with the stageplay export in John August's "Highland" app, which
itself seems to be based on Final Draft's "Broadway Musical" Template
(*not* the Dramatist Guild version) .  Lyrics are well handled in these.
Should you want PDFs or specs of these, just let me know.

Anyway I'm still amazed by your emacs implementation.  It seems to blend
the best features of writing in fountain in Slugline, Highland, and Sublime
Text!

**Comment by rnkn** [comment]
Could you have a look at the `"stageplay"` values in the highlighted block of code here and let me know if they're what you'd expect for a stageplay? They represent the default column integer to which stageplay elements should be aligned.

https://github.com/rnkn/fountain-mode/blob/develop/fountain-mode.el#L480-L550

**Comment by rnkn** [comment]
I've just tagged v2.0 that allows aligning action and allows aligning elements to different columns based on the document `format` metadata. Should be on MELPA-stable soon.
