### ISSUE TITLE
non courier font on Aquamacs

### ISSUE THREAD

**Issue by jcasu** [rnkn/fountain-mode#36]
apologies, but emacs noob.
When I start fountain mode under Aquamacs, my file is displayed in a non-fixed font, despite setting Courier-Prime as my default font everywhere.

How do I fix this?
thanks.

**Comment by rnkn** [comment]
This is odd. I'm not really familiar with Aquamacs, but it should be the same as GNU Emacs. Fountain mode faces don't really specify much, they just inherit from the font-lock default faces, which are set by whichever theme you're using, so it's hard to say what's doing this.

What happens when you position the cursor over some action text and `M-x describe-text-properties`? Likewise with a scene heading?

This is what you should get for action:
~~~
There are text properties here:
  fontified            t
~~~
And for a scene heading:
~~~
There are text properties here:
  face                 fountain-scene-heading
  fontified            t
  fountain-element     "scene-heading"
~~~

If you `M-x describe-face` on a scene heading you should get the following:
~~~
Documentation:
Default face for scene headings.

Defined in `fountain-mode.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: font-lock-function-name-face
~~~

Let me know if you get something different.
