### ISSUE TITLE
possible to export from an org-mode document with code blocks in fountain format?

### ISSUE THREAD

**Issue by incandescentman** [rnkn/fountain-mode#41]
Is it possible to make org-mode export fountain to HTML when it's in a larger org-mode file containing fountain-mode blocks here and there? I have a document that's mostly written in org-mode, with headings etc, but here and there I have source code blocks like this:

```
* Conflict and Character  
This monologue from /The Social Network/ is another great example of a monologue
that defines the character's values at the same time as deepening the conflict
with his antagonists.

#+BEGIN_SRC fountain 
GAGE
Do you think I deserve your full attention?

MARK
I had to swear an oath before we began this deposition, and I don't want to 
perjure myself, so I have a legal obligation to say no.

GAGE
Okay... "No," you don't think I deserve your attention?

MARK
I think if your clients want to sit on my shoulders and call themselves tall
they have a right to give it a try. But there's no requirement that I enjoy
sitting here listening to people lie. You have _part_ of my attention--you have
the minimum amount. The rest of my attention is back at the offices of Facebook
where my colleagues and I are doing things that no one in this room, including
and especially your clients, are intellectually or creatively capable of doing.
Did I adequately answer your condescending question?
#+END_SRC
```

It would be great to be able to export the entire org-mode document to HTML, with org-mode syntax and fountain-mode syntax each converted to their corresponding HTML format.

**Comment by rnkn** [comment]
I'm pretty unfamiliar with how Org-mode source code blocks work, but from what I can tell there are two issues that would make this unlikely.

The first is that the languages seem to be part of Org-mode, although there seems to be a way to add one's own with Babel (although I've never used this so have no idea really).

The second is that looking at a quick Org file export, it seems that code blocks are just exported as `<pre>` blocks, which limits any element styling like in HTML export from Fountain.

But it would be cool, so I'm happy to be proved wrong. The v2.0 parser would work well for these sort of snippets.

**Comment by rnkn** [comment]
Actually the better way to do it, I think, would be as an include file: http://orgmode.org/manual/Include-files.html#Include-files

I don't use Org-mode anymore but I'm pretty sure there is a way to run arbitrary code, so what you could do, in your Org file, is run a conversion from your Fountain source to HTML, then include the resulting file in the Org file, which you then export to HTML.

**Comment by incandescentman** [comment]
Including pre-generated HTML files would be a great solution. I'll look into it, thanks!

**Comment by rnkn** [comment]
Would it suit your workflow best to export a Fountain file as an HTML snippet (i.e. not a standalone document) together with a separate CSS file? That way you'd include the CSS file in your Org file's header once, then multiple HTML snippets as included files throughout.

**Comment by incandescentman** [comment]
Sure. How would I attach the CSS file to the fountain-mode source? Just using

**Comment by rnkn** [comment]
I've been working on [McQueen](https://github.com/rnkn/mcqueen), which has formed the HTML/CSS part of Fountain Mode v2.0. In the sample folder you'll see `sample.html` and `snippet.html`. You can see a live preview of [snippet.html here](https://rawgit.com/rnkn/mcqueen/master/sample/snippet.html). The McQueen stylesheet styles everything with a `.screenplay` class, so it won't interfere with your existing HTML content.

If you export a Fountain file with `fountain-export-inline-style nil` (`fountain-export-html-inline-style nil` in v2.0) you'll get a separate stylesheet file, which you can include in your Org file header exactly as you put. The snippets, as they will export wrapped in `class="screenplay"` will then be styled as screenplay, while the rest is styled by your own stylesheet.

Sorry you've kinda caught the project in a limbo before a major upgrade.

**Comment by rnkn** [comment]
This should be possible somehow with the current version. I just gotta look into it more.

**Comment by rnkn** [comment]
Sorry it has taken a while for me to look into this. Recently I removed the option to export using an external stylesheet because it made my life a lot easier, but this might ruin your workflow.

It seems easy to include an entire script, e.g. export Fountain → HTML, then in your Org file:
~~~
#+INCLUDE: "Script.html" html
~~~

Including snippets is a little more involved. To export regions from a single Fountain file, you'd need to narrow to a region, then export HTML and write each export to a different filename, then include each of those in your Org file.

The annoying thing is that this includes the entire inline stylesheet again.

To avoid this, you could first export a standalone HTML script, delete everything but the style header and save as `screenplay.css` to include in your Org file, then go back and set `fountain-export-standalone` to nil, and export your snippets, saving as e.g. `snippet-1.html` and `snippet-2.html` etc.

Snippets aren't wrapped in the necessary `class=screenplay` div, so you'd have to explicitly include those in your Org file:
~~~
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="screenplay.css" />

* Excerpt from Screenplay

#+HTML: <div class="screenplay">
#+INCLUDE: "snippet-1.html" html
#+HTML: </div>

* Another excerpt from Screenplay

#+HTML: <div class="screenplay">
#+INCLUDE: "snippet-2.html" html
#+HTML: </div>
~~~

Does any of this suit your current workflow?

**Comment by incandescentman** [comment]
Well, the appeal of using org-mode is that it allows you to maintain different formats all in one file. You can do this with code blocks with different [writing genres](http://orgmode.org/manual/Paragraphs.html), including poetry. It would be cool to have the ability to write commentary in the same file as the screenplay, as in my example above. Your suggested solution works, but it's just less convenient to maintain two separate files... and harder to view the screenplay you want to write commentary on.

**Comment by rnkn** [comment]
Sorry I never really gave this my full attention, but I’m closing now as I’ve removed the Elisp-based export functionality in favour of interfacing with external tools, which do a much better, faster and easier job of converting fountain files to various formats.
