### ISSUE TITLE
Export directly to pdf (via LaTeX) 

### ISSUE THREAD

**Issue by tty-tourist** [rnkn/fountain-mode#51]
It would be nice to have an option to export directty to pdf, that is, via LaTeX but without creating a tex buffer or file.

Something akin to `org-latex-export-to-pdf` in orgmode.

In addition, there would probably have to be a couple of variables to customize the file name used and whether an existing pdf should be overwritten.

**Comment by nicholascarroll** [comment]
Yes please implement it using the same pdflatex technology that org-mode uses. because the latex getting generated now seems to have unsupported fonts or something preventing it from generating the pdf. It would help alot to know that a working org-mode latex-pdf install is also going to work for fountain mode. THANKS

**Comment by rnkn** [comment]
I think the reason I didn't do it this way is because in order to do the TeX typesetting, the `.tex` file needs to be written to disk, which may overwrite an existing file. I think Org Mode does this without warning, and it's how I made the old HTML exporter work, but I don't think overwriting a file without warning is the way to go.

I'll have a look into adding an overwrite Y/N prompt to the export, then adding an export hook. Ideally each format should have its own hook, so this might need to be saved in `fountain-export-templates`.

**Comment by rnkn** [comment]
@nicholascarroll the default TeX template is written for XeTeX, so needs to be run through `xelatex` not `pdflatex`. I think this is why you might be getting font errors. Fountain Mode will always have different dependencies to Org Mode as they're just different programs. Although Fountain Mode needs fewer. Try the following in your shell:
```
$ sudo tlmgr install geometry fontspec titling fancyhdr marginnote ulem xstring oberdiek
```
Most of these will be there already.

**Comment by nicholascarroll** [comment]
OK thanks for the explanation. But certainly I agree export direct to PDF is useful and the intermediary step of tex isn't of value - its only a screenplay document.

**Comment by rnkn** [comment]
What if you have a screenplay called `Space Ham.fountain`, based on your novel of the same name, the manuscript of which is in the same directory as `Space Ham.tex`?

**Comment by nicholascarroll** [comment]
I see your point now.

**Comment by rnkn** [comment]
What about if there was `fountain-export-tex-hook` where you could add e.g. `TeX-command-buffer`?

**Comment by nicholascarroll** [comment]
that would be good enough.

thanks

**Comment by rnkn** [comment]
Are you on MELPA or MELPA-stable? The MELPA version should have the hook options within the next 24 hours.

There are a few other backend changes, like splitting up the export templates.

**Comment by nicholascarroll** [comment]
Yes i have MELPA is it version 20160720.2346 ?

**Comment by rnkn** [comment]
Looks like it. Let me know how it goes.

 `M-x customize-option RET fountain-export-tex-hook RET`

If using AUCTeX you'll need to have that loaded first `M-: (load-library "auctex")`

**Comment by nicholascarroll** [comment]
thanks, I'll let you know how it goes

**Comment by nicholascarroll** [comment]
Sorry I forgot to check this! I can't say when I'll have time.

**Comment by rnkn** [comment]
The hooks work pretty reliably. Soon you'll be able to export directly to PostScript (and then open that file as PDF) without LaTeX.

**Comment by taohansen** [comment]
Is PostScript support implemented?

**Comment by rnkn** [comment]
Not yet. It might be a while before I get to it. In the meantime I encourage [afterwriting-cli](https://github.com/ifrost/afterwriting-labs/blob/master/docs/clients.md).
