### ISSUE TITLE
MELPA install creates error

### ISSUE THREAD

**Issue by cdr255** [rnkn/fountain-mode#66]
I've used fountain for a while, but until recently I think I've clone it here from github. Recently, I've tried to install it from MELPA, but I keep getting this error:

`Symbol's value as variable is void: fountain-metadata-skeleton`

It halts the loading of my config, and although it seems fountain-mode is indeed installed. I'm on Emacs 24.4, and the error occurs whether in with-x or no-x. 

Looking for the variable, I see no fountain-* variables at all defined. 

If I install fountain-mode.el from the github repo (locally, without using package.el at all) there are many variables defined, and no error... So I think it has to do with the version hosted on MELPA. I can post the --debug-init backtrace if it'd be helpful, but I'm not familiar enough with elisp to offer a solution.

**Comment by rnkn** [comment]
Thanks for reporting this. Can you delete (not comment) this line in `fountain-mode.el`, relaunch Emacs and let me know if it solves?
https://github.com/rnkn/fountain-mode/blob/57567cfa879acef36e396138795a48c4405023ed/fountain-mode.el#L3761

**Comment by rnkn** [comment]
I just reinstalled fountain-mode from MELPA with `emacs -q` and didn't get any errors. Do you have
`(require fountain-mode)`
in you init file? If so, remove that. Packages don't need to be required.

**Comment by cdr255** [comment]
Removing line 3761 didn't fix the issue. I also removed the compiled version, just in case, but that didn't do anything either.

I added `(require fountain-mode)` only when I mean to load the version I have from github. I've removed it for debugging.

I thought it could just be something with my setup, so I moved my .emacs.d/ and started fresh (with `emacs -q` for good measure). From clean install, I added MELPA to my package list and then installed fountain-mode only. It complains twice, once about functions not being defined at runtime and once about a group of functions not known to be defined, but gives no immediate error. At this point, I can start emacs without an error and with everything for fountain-mode working.

I think I've tracked down the package that isn't playing nice through the backtrace. It seems that MELPA's packages for abc-mode and fountain-mode don't play well together. Removing MELPA's abc-mode from my original setup makes MELPA's fountain-mode load without a problem.

I don't know what the conflict is, though. I've opened an [issue](https://github.com/mkjunker/abc-mode/issues/3) on their github repo.

**Comment by rnkn** [comment]
No the bug is with fountain-mode not abc-mode. In the same directory as `fountain-mode.el` open `fountain-mode-autoloads.el` and delete:
~~~elisp
(with-eval-after-load 'autoinsert (define-auto-insert '(fountain-mode . "Fountain metadata skeleton") fountain-metadata-skeleton))
~~~
This is in addition to deleting line 3761 mentioned above.

I'll push a fix so it will be on MELPA in a few hours, but I've reproduced and fixed the error so I'm pretty sure this is it.

The problem was because the autoload declaration meant whenever anything loaded `autoinsert` I'd told it to add `fountain-metadata-skeleton` to its list of things to auto-insert, but that variable isn't defined until fountain-mode itself is read. abc-mode I assume was just the first to trigger.
