### ISSUE TITLE
avy-goto-char not working properly inside fountain-mode

### ISSUE THREAD

**Issue by SimonGZ** [rnkn/fountain-mode#85]
I'm having an odd interaction between [avy](https://github.com/abo-abo/avy) and fountain-mode.

When I first installed fountain-mode a year ago, avy worked fine and I could use it to jump to characters (text characters, not screenplay characters) within fountain-mode. But for some reason now I just get the message "zero candidates" whenever I try to use it.

Avy is still working for me in all other text modes. I've tried to do some debugging and I feel like some interaction between fountain-mode and avy may be causing avy to look in the wrong window, but I couldn't track down anything past that and I don't see any obvious reason why fountain-mode would affect it.

I understand this may be out of scope as a fountain-mode problem, but I can't find any other situations where it's misbehaving and I thought you might have an idea what's going on.

(P.S.: Thanks for the great screenwriting mode and also McQueen.)

**Comment by rnkn** [comment]
I've done a bit of investigating and I'm pretty certain it's a bug with `avy--next-visible-point` and/or `avy—next-invisible-point`. These functions consider any text with the `invisible` text property to be invisible, and so exclude it from searching. However that's not how Emacs's text visibility works; text is only invisible if the cdr of the `invisible` text property is included in the variable `buffer-invisibility-spec`.

This is only a problem with fountain-mode because a while ago I made every element have an invisibility property, with the idea that eventually it would be possible to show/hide any element in a script (which you can do now with `M-: (add-to-invisibility-spec 'action)` but the element boundaries aren't right). It's actually not at all useful in its current form so I could remove it, but technically the bug lies with avy.

**Comment by rnkn** [comment]
p.s. I checked out your website back when you cloned McQueen. Did you use fountain-mode with _Santa Clarita Diet_? If so that's pretty cool 😎

**Comment by rnkn** [comment]
The invisible text properties have been removed in the master branch. I've tested out avy and it works.

**Comment by SimonGZ** [comment]
Wow. Thanks so much for immediately diagnosing this, putting out a fix, and opening an issue in the proper place. Tremendously efficient!

And yes, I did get to use fountain-mode a little bit on Santa Clarita Diet while writing my episode, though I haven't yet written a full episode in it. Maybe this year! Thanks again for all the great fountain projects.

**Comment by rnkn** [comment]
No worries. It's really a product of procrastination. Technically this isn't 100% fixed; avy will still fail to find characters like `=` at the start of a synopsis, or emphasis delimiters, because these can be hidden by design.

Can I ask a favour? I'd really love to hear more about your work. Would you be open to emailing me about how you got started and all that?

**Comment by SimonGZ** [comment]
Sure. Happy to email (or hop on the phone if we can work out the time difference). Is the email on your website okay?

**Comment by rnkn** [comment]
Awesome. Yep if you email me at hello@paulwrankin.com we can sort something.
